#version 300 es
// psAlphaTestTexture (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psAlphaTestTexture.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    r0 = clamp(t0, -1.0, 1.0);
    if (r0.a < alphaRef) discard;   // D3DRS_ALPHATEST for this shader
    fragColor = clamp(r0, 0.0, 1.0);
}
