#version 300 es
// psBumpedMirror (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psBumpedMirror.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s3;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    float m3x3_1 = dot(vT1.xyz, ((t0 * 2.0 - 1.0)).xyz);
    float m3x3_2 = dot(vT2.xyz, ((t0 * 2.0 - 1.0)).xyz);
    float m3x3_3 = dot(vT3.xyz, ((t0 * 2.0 - 1.0)).xyz);
    vec3 m3x3_N = vec3(m3x3_1, m3x3_2, m3x3_3);
    vec3 m3x3_E = vec3(vT1.w, vT2.w, vT3.w);
    vec3 m3x3_R = 2.0 * dot(m3x3_N, m3x3_E) * m3x3_N - dot(m3x3_N, m3x3_N) * m3x3_E;
    vec4 t3 = texture(s3, (vec4(m3x3_R, 1.0)).xy);
    r0 = clamp(t3, -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
