#version 300 es
// psBumpedFresnel (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psBumpedFresnel.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    vec4 t1 = texture(s1, (vT1).xy);
    vec4 t2 = texture(s2, (vT2).xy);
    vec4 co_a3 = clamp(vec4(dot(((t0 * 2.0 - 1.0)).xyz, ((t2 * 2.0 - 1.0)).xyz)), -1.0, 1.0);
    vec4 co_b3 = clamp((pc[0].wwww * t1.wwww), -1.0, 1.0);
    r1.xyz = (co_a3).xyz;
    r0.w = (co_b3).w;
    vec4 co_a5 = clamp(((1.0 - r1) * (1.0 - r1)), -1.0, 1.0);
    vec4 co_b5 = clamp((pc[0].zzzz * t1.wwww), -1.0, 1.0);
    r1.xyz = (co_a5).xyz;
    r1.w = (co_b5).w;
    r1.xyz = (clamp((r1 * r1), -1.0, 1.0)).xyz;
    vec4 co_a8 = clamp(t1, -1.0, 1.0);
    vec4 co_b8 = clamp((r1.wwww * r1.zzzz + r0.wwww), -1.0, 1.0);
    r0.xyz = (co_a8).xyz;
    r0.w = (co_b8).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
