#version 300 es
// psCalcNH (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psCalcNH.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    vec4 t1 = texture(s1, (vT1).xy);
    vec4 t2 = clamp(vT2, 0.0, 1.0);
    r1.xyz = (clamp((t0 - t1), -1.0, 1.0)).xyz;
    r1 = clamp(vec4(dot((r1).xyz, (r1).xyz)), -1.0, 1.0);
    vec4 co_a5 = clamp(((t0 - t1) * 2.0), -1.0, 1.0);
    vec4 co_b5 = clamp((pc[0] * r1 + pc[0]), -1.0, 1.0);
    r0.xyz = (co_a5).xyz;
    r1.w = (co_b5).w;
    r0 = clamp(vec4(dot((r0).xyz, (r0).xyz)), -1.0, 1.0);
    vec4 co_a8 = clamp(pc[0], -1.0, 1.0);
    vec4 co_b8 = clamp(((r0.wwww).x > 0.5 ? r1 : r0), -1.0, 1.0);
    r0.xyz = (co_a8).xyz;
    r0.w = (co_b8).w;
    r1 = clamp((vec4(dot(((t0 * 2.0 - 1.0)).xyz, ((t2 * 2.0 - 1.0)).xyz)) * 4.0), -1.0, 1.0);
    r1 = clamp((r1 * 4.0), 0.0, 1.0);
    r0 = clamp(mix(pc[1], r0, r1.wwww), -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
