#version 300 es
// psCalcNHBumped (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psCalcNHBumped.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r4 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    r0 = texture(s0, (vT0).xy);
    r1 = texture(s1, (vT1).xy);
    r2.xyz = (vT2).xyz;
    r5.xyz = (clamp((r0 - r1), -1.0, 1.0)).xyz;
    r5 = clamp(vec4(dot((r5).xyz, (r5).xyz)), -1.0, 1.0);
    vec4 co_a5 = clamp(((r0 - r1) * 2.0), -1.0, 1.0);
    vec4 co_b5 = clamp((pc[0] * r5 + pc[0]), -1.0, 1.0);
    r4.xyz = (co_a5).xyz;
    r5.w = (co_b5).w;
    r4 = clamp(vec4(dot((r4).xyz, (r4).xyz)), -1.0, 1.0);
    vec4 co_a8 = clamp(r0.wwww, -1.0, 1.0);
    vec4 co_b8 = clamp(mix(r4, r5, vec4(greaterThan(r4.wwww, vec4(0.5)))), -1.0, 1.0);
    r4.xyz = (co_a8).xyz;
    r4.w = (co_b8).w;
    r5 = clamp((vec4(dot((pc[2]).xyz, ((r2 * 2.0 - 1.0)).xyz)) * 8.0), 0.0, 1.0);
    r4.w = (clamp(mix(pc[1], r4, r5.wwww), -1.0, 1.0)).w;
    r0 = clamp(r4, -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
