#version 300 es
// psCLSkyLight3 (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psCLSkyLight3.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    vec4 t1 = texture(s1, (vT1).xy);
    vec4 t2 = texture(s2, (vT2).xy);
    r0 = clamp((t0 + (-vD0)), 0.0, 1.0);
    r1 = clamp((t1 + (-vD0)), 0.0, 1.0);
    r0 = clamp(mix(r1, r0, pc[0]), -1.0, 1.0);
    r1 = clamp((t2 + (-vD0)), 0.0, 1.0);
    r0 = clamp((mix(r0, r1, pc[1]) * 4.0), -1.0, 1.0);
    r0 = clamp(((r0 + r0) * 4.0), 0.0, 1.0);
    r0 = clamp(((r0 + r0) * 4.0), 0.0, 1.0);
    r0 = clamp(vec4(dot(((1.0 - r0)).xyz, (vD1).xyz)), -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
