#version 300 es
// psDiffuseTFactor4 (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psDiffuseTFactor4.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    r0 = clamp(((vD0 * pc[0]) * 4.0), -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
