#version 300 es
// psDynLMPerPixel4 (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psDynLMPerPixel4.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    r0 = texture(s0, (vT0).xy);
    r1 = textureProj(s1, (vT1).xyw);
    r5 = clamp(vec4(dot(((r0 * 2.0 - 1.0)).xyz, (pc[0]).xyz)), 0.0, 1.0);
    r5.xyz = (clamp((r5 * pc[1]), -1.0, 1.0)).xyz;
    r5 = clamp((r5 * r1 + vD0), -1.0, 1.0);
    vec4 co_a5 = clamp(((r5 * pc[2]) * 4.0), -1.0, 1.0);
    vec4 co_b5 = clamp(pc[2].wwww, -1.0, 1.0);
    r0.xyz = (co_a5).xyz;
    r0.w = (co_b5).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
