#version 300 es
// psFastFullBump4 (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psFastFullBump4.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
uniform sampler2D s3;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    vec4 r4 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    r0 = texture(s0, (vT0).xy);
    r1 = texture(s1, (vT1).xy);
    r2 = textureProj(s2, (vT2).xyw);
    r3 = textureProj(s3, (vT3).xyw);
    r4 = clamp(vec4(dot(((r0 * 2.0 - 1.0)).xyz, ((vD0 * 2.0 - 1.0)).xyz)), 0.0, 1.0);
    vec4 co_a5 = clamp(vec4(dot(((r0 * 2.0 - 1.0)).xyz, ((vD1 * 2.0 - 1.0)).xyz)), -1.0, 1.0);
    vec4 co_b5 = clamp((r4.wwww * vD1.wwww), -1.0, 1.0);
    r5.xyz = (co_a5).xyz;
    r4.w = (co_b5).w;
    r5.xyz = (clamp((r5 * pc[2] + pc[1]), -1.0, 1.0)).xyz;
    r5.xyz = (clamp((r5 * r2.wwww + r2), -1.0, 1.0)).xyz;
    r5.xyz = (clamp((r5 * r1), -1.0, 1.0)).xyz;
    r4.xyz = (clamp((r4.wwww * pc[3]), -1.0, 1.0)).xyz;
    vec4 co_a11 = clamp((r4 * r3), -1.0, 1.0);
    vec4 co_b11 = clamp(r2.wwww, -1.0, 1.0);
    r4.xyz = (co_a11).xyz;
    r0.w = (co_b11).w;
    r0.xyz = (clamp(((r4 * r1 + r5) * 4.0), -1.0, 1.0)).xyz;
    fragColor = clamp(r0, 0.0, 1.0);
}
