#version 300 es
// psFoggedParticle (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psFoggedParticle.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    vec4 t1 = texture(s1, (vT1).xy);
    r0 = clamp((t0 * t1.wwww), -1.0, 1.0);
    vec4 co_a3 = clamp((t1 * (1.0 - t0.wwww) + r0), -1.0, 1.0);
    vec4 co_b3 = clamp(t1.wwww, -1.0, 1.0);
    r0.xyz = (co_a3).xyz;
    r0.w = (co_b3).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
