#version 300 es
// psFullPerPixelTexSpecular (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psFullPerPixelTexSpecular.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
uniform sampler2D s3;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    r0 = textureProj(s0, (vT0).xyw);
    r0.x = (clamp(r0.wwww, -1.0, 1.0)).x;
    r1 = texture(s1, (r0).xy);
    r2 = texture(s2, (vT2).xy);
    r3 = texture(s3, (vT3).xy);
    r0 = clamp((r1 * vD0), -1.0, 1.0);
    r0 = clamp((r0 * r2), -1.0, 1.0);
    r0 = clamp((r0 * r3), -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
