#version 300 es
// psLMPDTexture (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psLMPDTexture.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    r0 = textureProj(s0, (vT0).xyw);
    r1 = texture(s1, (vT1).xy);
    r0 = clamp((vD0 * r0.wwww + r0), -1.0, 1.0);
    vec4 co_a3 = clamp(((r0 * r1) * 4.0), 0.0, 1.0);
    vec4 co_b3 = clamp((r0.wwww + (1.0 - r0.wwww)), -1.0, 1.0);
    r0.xyz = (co_a3).xyz;
    r0.w = (co_b3).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
