#version 300 es
// psPerPixelFullTex4 (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psPerPixelFullTex4.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
uniform sampler2D s3;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    r0 = texture(s0, (vT0).xy);
    r1 = texture(s1, (vT1).xy);
    r2 = textureProj(s2, (vT2).xyw);
    r3 = textureProj(s3, (vT3).xyw);
    r5 = clamp(vec4(dot(((r1 * 2.0 - 1.0)).xyz, (pc[0]).xyz)), 0.0, 1.0);
    r5.xyz = (clamp((pc[1] * r5), -1.0, 1.0)).xyz;
    r1 = clamp((vD0 * r2.wwww + r2), -1.0, 1.0);
    r1 = clamp(((r1 * r0) * 4.0), 0.0, 1.0);
    r5 = clamp((r5 * r3), -1.0, 1.0);
    r5 = clamp(((r5 * r0) * 4.0), 0.0, 1.0);
    r0.xyz = (clamp((r5 + r1), -1.0, 1.0)).xyz;
    fragColor = clamp(r0, 0.0, 1.0);
}
