#version 300 es
// psProjectedTexture (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psProjectedTexture.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    r0 = textureProj(s0, (vT0).xyw);
    fragColor = clamp(r0, 0.0, 1.0);
}
