#version 300 es
// psShadowTestSmoothed (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psShadowTestSmoothed.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    r0 = textureProj(s0, (vT0).xyw);
    r1 = clamp((r0 + (-vD0)), 0.0, 1.0);
    r1 = clamp((vec4(dot((r1).xyz, (pc[0]).xyz)) * 4.0), -1.0, 1.0);
    vec4 co_a3 = clamp((r0 + (1.0 - r0)), -1.0, 1.0);
    vec4 co_b3 = clamp((r1 + pc[1]), -1.0, 1.0);
    r0.xyz = (co_a3).xyz;
    r0.w = (co_b3).w;
    vec4 co_a5 = clamp(mix(r0, pc[1], vec4(greaterThan(r0.wwww, vec4(0.5)))), -1.0, 1.0);
    vec4 co_b5 = clamp((vD0.wwww + vD1.wwww), -1.0, 1.0);
    r0.xyz = (co_a5).xyz;
    r0.w = (co_b5).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
