#version 300 es
// psShadowBlur (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psShadowBlur.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s1;
uniform sampler2D s2;
uniform sampler2D s3;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    vec4 t1 = texture(s1, (vT1).xy);
    vec4 t2 = texture(s2, (vT2).xy);
    vec4 t3 = texture(s3, (vT3).xy);
    r0.w = (clamp(((t0.wwww + (-t1.wwww)) * 4.0), -1.0, 1.0)).w;
    r0.w = (clamp((r0.wwww * r0.wwww + pc[0].wwww), -1.0, 1.0)).w;
    vec4 co_a6 = clamp(((r0.wwww).x > 0.5 ? t0 : t1), -1.0, 1.0);
    vec4 co_b6 = clamp(((t0.wwww + (-t2.wwww)) * 4.0), -1.0, 1.0);
    r1.xyz = (co_a6).xyz;
    r0.w = (co_b6).w;
    vec4 co_a8 = clamp(mix(r1, t0, pc[1].wwww), -1.0, 1.0);
    vec4 co_b8 = clamp((r0.wwww * r0.wwww + pc[0].wwww), -1.0, 1.0);
    r0.xyz = (co_a8).xyz;
    r0.w = (co_b8).w;
    vec4 co_a10 = clamp(((r0.wwww).x > 0.5 ? t0 : t2), -1.0, 1.0);
    vec4 co_b10 = clamp(((t0.wwww + (-t3.wwww)) * 4.0), -1.0, 1.0);
    r1.xyz = (co_a10).xyz;
    r0.w = (co_b10).w;
    vec4 co_a12 = clamp(mix(r1, r0, pc[2].wwww), -1.0, 1.0);
    vec4 co_b12 = clamp((r0.wwww * r0.wwww + pc[0].wwww), -1.0, 1.0);
    r0.xyz = (co_a12).xyz;
    r0.w = (co_b12).w;
    r1.xyz = (clamp(((r0.wwww).x > 0.5 ? t0 : t3), -1.0, 1.0)).xyz;
    r0.xyz = (clamp(mix(r1, r0, pc[3].wwww), -1.0, 1.0)).xyz;
    fragColor = clamp(r0, 0.0, 1.0);
}
