#version 300 es
// psSoftShadowTest (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psSoftShadowTest.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    r0 = textureProj(s0, (vT0).xyw);
    r0 = clamp((r0 + (-vD0)), 0.0, 1.0);
    r0 = clamp(vec4(dot((r0).xyz, (pc[0]).xyz)), -1.0, 1.0);
    vec4 co_a3 = clamp(pc[1], -1.0, 1.0);
    vec4 co_b3 = clamp(((r0 + r0) * 4.0), -1.0, 1.0);
    r0.xyz = (co_a3).xyz;
    r0.w = (co_b3).w;
    r0.w = (clamp(((1.0 - r0) * 2.0), -1.0, 1.0)).w;
    fragColor = clamp(r0, 0.0, 1.0);
}
