#version 300 es
// psTexturedFog (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psTexturedFog.psh
precision mediump float;
uniform vec4 pc[8];
uniform float alphaRef;   // alpha test reference (0..1); ignored unless the shader tests
uniform sampler2D s0;
uniform sampler2D s2;
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = texture(s0, (vT0).xy);
    float m3x2_u = dot(vT1.xyz, (t0).xyz);
    float m3x2_v = dot(vT2.xyz, (t0).xyz);
    vec4 t2 = texture(s2, (vec4(m3x2_u, m3x2_v, 0.0, 1.0)).xy);
    r0 = clamp(t2, -1.0, 1.0);
    fragColor = clamp(r0, 0.0, 1.0);
}
