#version 300 es
// vsAlienEffect -- generated by tools/d3dasm2glsl.py from shaders/d3d/vs/vsAlienEffect.vsh
precision highp float;
layout(location = 0) in vec3 a_pos;
layout(location = 1) in vec4 a_normal;    // D3DCOLOR: memory b,g,r,a
layout(location = 3) in vec2 a_tex0;      // SHORT2, unnormalized
layout(location = 4) in vec4 a_tangent0;  // D3DCOLOR
layout(location = 5) in vec4 a_tangent1;  // D3DCOLOR
layout(location = 6) in vec2 a_tex1;      // SHORT2, unnormalized
uniform vec4 vc[96];
uniform vec4 posFixup;    // x: y flip (+1 / -1), z: 1/viewportW, w: -1/viewportH
out vec4 vD0;
out vec4 vD1;
out vec4 vT0;
out vec4 vT1;
out vec4 vT2;
out vec4 vT3;
void main()
{
    vec4 o_pos = vec4(0.0);
    vD0 = vec4(0.0); vD1 = vec4(0.0);
    vT0 = vec4(0.0); vT1 = vec4(0.0); vT2 = vec4(0.0); vT3 = vec4(0.0);
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    vec4 r4 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    vec4 r7 = vec4(0.0);
    r4 = vec4(dot(vec4(a_pos, 1.0), vc[10]), dot(vec4(a_pos, 1.0), vc[11]), dot(vec4(a_pos, 1.0), vc[12]), dot(vec4(a_pos, 1.0), vc[13]));
    o_pos = r4;
    r5.xy = ((vc[7].zwww * r4.wwww)).xy;
    r4.xy = ((r4.xyyy * vc[7].xyyy + r5.xyyy)).xy;
    r0 = r4.xyww;
    r2.xyz = ((a_normal.zyxw * vc[3].xxxx + vc[3].yyyy)).xyz;
    r4.xyz = ((vc[9].xyzz + (-vec4(a_pos, 1.0).xyzz))).xyz;
    r4.w = (vec4(dot((r4).xyz, (r4).xyz))).w;
    r7.w = (vec4(inversesqrt(abs((r4.wwww).x)))).w;
    r4.xyz = ((r4.xyzz * r7.wwww)).xyz;
    r4.w = (vec4(dot((r4).xyz, (r2).xyz))).w;
    r5.w = ((vc[1].xxxx + (-r4.wwww))).w;
    r5.w = ((r5.wwww * r5.wwww)).w;
    r5.w = ((r5.wwww * r5.wwww)).w;
    r4.w = ((r4.wwww * vc[2].zzzz)).w;
    vD0.w = ((r5.wwww * vc[14].zzzz + vc[14].wwww)).w;
    vT1.xyz = ((r4.wwww * r2 + (-r4.xyzz))).xyz;
    r3.xyz = ((vc[9].xyzz + (-vec4(a_pos, 1.0).xyzz))).xyz;
    r3.w = (vec4(dot((r3).xyz, (r3).xyz))).w;
    r5.w = (vec4(inversesqrt(abs((r3.wwww).x)))).w;
    r3.xyz = ((r3.xyzz * r5.wwww)).xyz;
    r3.w = (vec4(dot((r3).xyz, (r3).xyz))).w;
    r4.w = (vec4(inversesqrt(abs((r3.wwww).x)))).w;
    r3.xyz = ((r3.xyzz * r4.wwww)).xyz;
    r1.z = (vec4(dot((r3).xyz, (r2).xyz))).z;
    r2.xyz = ((r3 * (-r1.zzzz) + r2)).xyz;
    r1.x = (vec4(dot((r2).xyz, (vc[16]).xyz))).x;
    r1.y = (vec4(dot((r2).xyz, (vc[17]).xyz))).y;
    r0.xy = ((r1.xyyy * r0.wwww + r0.xyyy)).xy;
    vT0 = r0;
    // D3D vertex-shader colour outputs are saturated.
    vD0 = clamp(vD0, 0.0, 1.0);
    vD1 = clamp(vD1, 0.0, 1.0);
    // D3D clip space -> GL: z from [0,w] to [-w,w]; optional y flip when
    // rendering into a texture (so the image lands top-down like D3D's);
    // half-pixel offset so D3D9's pixel-centre convention lines up.
    o_pos.y *= posFixup.x;
    o_pos.xy += posFixup.zw * o_pos.w;
    o_pos.z = o_pos.z * 2.0 - o_pos.w;
    gl_Position = o_pos;
}
