#version 300 es
// vsDirectionalTest -- generated by tools/d3dasm2glsl.py from shaders/d3d/vs/vsDirectionalTest.vsh
precision highp float;
layout(location = 0) in vec3 a_pos;
layout(location = 1) in vec4 a_normal;    // D3DCOLOR: memory b,g,r,a
layout(location = 3) in vec2 a_tex0;      // SHORT2, unnormalized
layout(location = 4) in vec4 a_tangent0;  // D3DCOLOR
layout(location = 5) in vec4 a_tangent1;  // D3DCOLOR
layout(location = 6) in vec2 a_tex1;      // SHORT2, unnormalized
uniform vec4 vc[96];
uniform vec4 posFixup;    // x: y flip (+1 / -1), z: 1/viewportW, w: -1/viewportH
out vec4 vD0;
out vec4 vD1;
out vec4 vT0;
out vec4 vT1;
out vec4 vT2;
out vec4 vT3;
void main()
{
    vec4 o_pos = vec4(0.0);
    vD0 = vec4(0.0); vD1 = vec4(0.0);
    vT0 = vec4(0.0); vT1 = vec4(0.0); vT2 = vec4(0.0); vT3 = vec4(0.0);
    vec4 r0 = vec4(0.0);
    o_pos = vec4(dot(vec4(a_pos, 1.0), vc[10]), dot(vec4(a_pos, 1.0), vc[11]), dot(vec4(a_pos, 1.0), vc[12]), dot(vec4(a_pos, 1.0), vc[13]));
    r0 = vec4(dot(vec4(a_pos, 1.0), vc[16]));
    vD0 = (r0 + vc[19]);
    vT0.x = (vec4(dot(vec4(a_pos, 1.0), vc[17]))).x;
    vT0.y = (vec4(dot(vec4(a_pos, 1.0), vc[18]))).y;
    // D3D vertex-shader colour outputs are saturated.
    vD0 = clamp(vD0, 0.0, 1.0);
    vD1 = clamp(vD1, 0.0, 1.0);
    // D3D clip space -> GL: z from [0,w] to [-w,w]; optional y flip when
    // rendering into a texture (so the image lands top-down like D3D's);
    // half-pixel offset so D3D9's pixel-centre convention lines up.
    o_pos.y *= posFixup.x;
    o_pos.xy += posFixup.zw * o_pos.w;
    o_pos.z = o_pos.z * 2.0 - o_pos.w;
    gl_Position = o_pos;
}
