#version 300 es
// vsDynLMPerPixel -- generated by tools/d3dasm2glsl.py from shaders/d3d/vs/vsDynLMPerPixel.vsh
precision highp float;
layout(location = 0) in vec3 a_pos;
layout(location = 1) in vec4 a_normal;    // D3DCOLOR: memory b,g,r,a
layout(location = 3) in vec2 a_tex0;      // SHORT2, unnormalized
layout(location = 4) in vec4 a_tangent0;  // D3DCOLOR
layout(location = 5) in vec4 a_tangent1;  // D3DCOLOR
layout(location = 6) in vec2 a_tex1;      // SHORT2, unnormalized
uniform vec4 vc[96];
uniform vec4 posFixup;    // x: y flip (+1 / -1), z: 1/viewportW, w: -1/viewportH
out vec4 vD0;
out vec4 vD1;
out vec4 vT0;
out vec4 vT1;
out vec4 vT2;
out vec4 vT3;
void main()
{
    vec4 o_pos = vec4(0.0);
    vD0 = vec4(0.0); vD1 = vec4(0.0);
    vT0 = vec4(0.0); vT1 = vec4(0.0); vT2 = vec4(0.0); vT3 = vec4(0.0);
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    r1 = vec4(dot(vec4(a_pos, 1.0), vc[10]), dot(vec4(a_pos, 1.0), vc[11]), dot(vec4(a_pos, 1.0), vc[12]), dot(vec4(a_pos, 1.0), vc[13]));
    o_pos = r1;
    r2.xy = ((vc[7].zwww * r1.wwww)).xy;
    r1.xy = ((r1.xyyy * vc[7].xyyy + r2.xyyy)).xy;
    vT1 = r1.xyww;
    r0.xyz = ((a_normal.zyxw * vc[3].xxxx + vc[3].yyyy)).xyz;
    vT0.xyz = (r0).xyz;
    r2.xyz = (max(r0, vc[0])).xyz;
    r1.xyz = ((vc[25] * r2.xxxx)).xyz;
    r1.xyz = ((vc[27] * r2.yyyy + r1)).xyz;
    r1.xyz = ((vc[29] * r2.zzzz + r1)).xyz;
    r3.xyz = (max((-r0), vc[0])).xyz;
    r1.xyz = ((vc[26] * r3.xxxx + r1)).xyz;
    r1.xyz = ((vc[28] * r3.yyyy + r1)).xyz;
    vD0.xyz = ((vc[30] * r3.zzzz + r1)).xyz;
    // D3D vertex-shader colour outputs are saturated.
    vD0 = clamp(vD0, 0.0, 1.0);
    vD1 = clamp(vD1, 0.0, 1.0);
    // D3D clip space -> GL: z from [0,w] to [-w,w]; optional y flip when
    // rendering into a texture (so the image lands top-down like D3D's);
    // half-pixel offset so D3D9's pixel-centre convention lines up.
    o_pos.y *= posFixup.x;
    o_pos.xy += posFixup.zw * o_pos.w;
    o_pos.z = o_pos.z * 2.0 - o_pos.w;
    gl_Position = o_pos;
}
