#version 300 es
// vsPrecisePointBump -- generated by tools/d3dasm2glsl.py from shaders/d3d/vs/vsPrecisePointBump.vsh
precision highp float;
layout(location = 0) in vec3 a_pos;
layout(location = 1) in vec4 a_normal;    // D3DCOLOR: memory b,g,r,a
layout(location = 3) in vec2 a_tex0;      // SHORT2, unnormalized
layout(location = 4) in vec4 a_tangent0;  // D3DCOLOR
layout(location = 5) in vec4 a_tangent1;  // D3DCOLOR
layout(location = 6) in vec2 a_tex1;      // SHORT2, unnormalized
uniform vec4 vc[96];
uniform vec4 posFixup;    // x: y flip (+1 / -1), z: 1/viewportW, w: -1/viewportH
out vec4 vD0;
out vec4 vD1;
out vec4 vT0;
out vec4 vT1;
out vec4 vT2;
out vec4 vT3;
void main()
{
    vec4 o_pos = vec4(0.0);
    vD0 = vec4(0.0); vD1 = vec4(0.0);
    vT0 = vec4(0.0); vT1 = vec4(0.0); vT2 = vec4(0.0); vT3 = vec4(0.0);
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    vec4 r4 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    vec4 r6 = vec4(0.0);
    vec4 r7 = vec4(0.0);
    vec4 r8 = vec4(0.0);
    o_pos = vec4(dot(vec4(a_pos, 1.0), vc[10]), dot(vec4(a_pos, 1.0), vc[11]), dot(vec4(a_pos, 1.0), vc[12]), dot(vec4(a_pos, 1.0), vc[13]));
    r3.xyz = ((a_normal.zyxw * vc[3].xxxx + vc[3].yyyy)).xyz;
    r4.xyz = ((a_tangent0.zyxw * vc[3].xxxx + vc[3].yyyy)).xyz;
    r5.xyz = ((a_tangent1.zyxw * vc[3].xxxx + vc[3].yyyy)).xyz;
    r0.xyz = ((vc[15] - vec4(a_pos, 1.0))).xyz;
    r1.x = (vec4(dot((r0).xyz, (r3).xyz))).x;
    r1.y = ((r1.xxxx * vc[21].zzzz)).y;
    r1.y = ((r1.yyyy * vc[4].zzzz)).y;
    r1.y = ((r1.yyyy * r1.yyyy)).y;
    r1.w = ((r1.yyyy + vc[1].xxxx)).w;
    r1.w = (vec4(1.0 / (r1.wwww).x)).w;
    r1.z = (vec4(inversesqrt(abs((r1.wwww).x)))).z;
    r1.y = ((r1.yyyy * r1.yyyy)).y;
    r1.y = ((r1.yyyy * r1.yyyy + vc[4].wwww)).y;
    r1.y = (vec4(1.0 / (r1.yyyy).x)).y;
    r1.y = ((r1.yyyy * vc[4].wwww)).y;
    r1.w = ((r1.yyyy * r1.wwww)).w;
    r6.x = (vec4(dot((r3).xyz, (r0).xyz))).x;
    r6.x = (vec4(greaterThanEqual(r6.xxxx, vc[0].xxxx))).x;
    r6.x = ((r6.xxxx * r1.wwww)).x;
    vD0 = (r6.xxxx * vc[14]);
    r8.x = (vec4(dot((r4).xyz, (r0).xyz))).x;
    r8.y = (vec4(dot((r5).xyz, (r0).xyz))).y;
    r8.w = ((r1.zzzz * vc[2].zzzz)).w;
    r8.xy = ((r8.xyyy * vc[21].zzzz + r1.zzzz)).xy;
    vT0 = r8.xyww;
    r7.x = (vec4(dot((r4).xyz, (r0).xyz))).x;
    r7.y = (vec4(dot((r5).xyz, (r0).xyz))).y;
    r7.z = (vec4(dot((r3).xyz, (r0).xyz))).z;
    r7.w = (vec4(dot((r7).xyz, (r7).xyz))).w;
    r8.w = (vec4(inversesqrt(abs((r7.wwww).x)))).w;
    r7.xyz = ((r7.xyzz * r8.wwww)).xyz;
    vT1.xyz = (r7).xyz;
    vT2.xy = ((vec4(a_tex0, 0.0, 1.0) * vc[6].xxxx)).xy;
    vT3.xy = ((vec4(a_tex0, 0.0, 1.0) * vc[6].xxxx)).xy;
    // D3D vertex-shader colour outputs are saturated.
    vD0 = clamp(vD0, 0.0, 1.0);
    vD1 = clamp(vD1, 0.0, 1.0);
    // D3D clip space -> GL: z from [0,w] to [-w,w]; optional y flip when
    // rendering into a texture (so the image lands top-down like D3D's);
    // half-pixel offset so D3D9's pixel-centre convention lines up.
    o_pos.y *= posFixup.x;
    o_pos.xy += posFixup.zw * o_pos.w;
    o_pos.z = o_pos.z * 2.0 - o_pos.w;
    gl_Position = o_pos;
}
